name: CI Software Testing

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    # Menyalakan database MySQL di GitHub Actions
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toko_bahan_makanan_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Prepare Laravel Environment
        run: |
          cp .env.example .env.testing
          php artisan key:generate

      - name: Run Testing
        env:
          # Pastikan env ini sama dengan yang diatur di bagian 'services' di atas
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: toko_bahan_makanan_test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test